[tool.poetry]
name = "rut"
version = "0.1.0"
description = "A cli of r utilities aiamed at package and .Rprofile management."
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.6"
click = "^7.0"

[tool.poetry.dev-dependencies]
